name: BlockCityTycoonFoundry
version: '${project.version}'
main: me.darkmun.blockcitytycoonfoundry.BlockCityTycoonFoundry
authors: [ Darkmun ]
depend: [ ProtocolLib, PacketWrapper ]
commands:
  foundryfurnace:
    description: Добавление печки в плавильню